# Generated by Django 5.2.6 on 2025-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='admin_password',
            field=models.CharField(default=1, help_text='Plain text password (will be hashed)', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='admin_username',
            field=models.CharField(default='schooladmin', max_length=150),
        ),
    ]
