# Generated by Django 5.2.6 on 2025-10-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='competency',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacherassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='termconfig',
            unique_together={('year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplinerecord',
            unique_together={('student', 'year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('subject', 'classroom', 'teacher', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectenrollment',
            unique_together={('teacher_assignment', 'student')},
        ),
    ]
