# Generated by Django 5.2.6 on 2025-10-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_competency_teacher_alter_mark_teacher_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition'), ('registration', 'Registration'), ('books', 'Books'), ('uniform', 'Uniform'), ('transport', 'Transport'), ('exam', 'Examination'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.IntegerField()),
                ('term', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=10)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Leave blank for school-wide fees', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque/Transfer reference', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='academics.student')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.feestructure')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
            options={
                'ordering': ['-academic_year', '-term'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
    ]
